export type Shader = {
  uniforms: Record<string, { value: any }>;
  vertexShader: string;
  fragmentShader: string;
};

export const projectData = {
  nimeton: {
    title: "Nimetön",
    thumbnail: "/img/nimeton/nimeton.jpeg",
    genre: { program: false, design: true, plan: false },
    date: "2019年6月末頃～2019年8月初旬",
    period: "1か月程度",
    member: "1人",
    tasks: "none",
    skill:
      "アクリルガッシュ、ボールペン、カラーマジック、F50号パネル、ドリッピング",
    award1: "第71回高校展　奨励賞受賞",
    award2: "大阪府教育センターロビー展示作品　選出",
    description: `高校2年生の夏に美術部の活動の一環として制作した美術作品。
                  F50号パネルに画用紙を水張りし、アクリル絵具で制作した。
                  展示会では受賞や他校生からの推薦を頂けた思い出のある作品。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: `none`,
    release: `none`,
    github: `none`,
  },
  egg: {
    title: "たまごのモーニングルーティーン",
    thumbnail: "/img/egg/title.png",
    genre: { program: true, design: true, plan: true },
    date: "2021年8月～2021年9月頃",
    period: "1か月程度",
    member: "4人(プログラマー2名、2Dデザイナー1名、3Dデザイナー1名)",
    tasks: `企画…考案、仕様書作成、進捗管理など
            デザイン…農夫キャラクターデザイン、フィールド作成
            プログラミングと実装…インゲーム全般`,
    skill: "C#、Unity、GitHub",
    award1: "none",
    award2: "none",
    description: `人生で初めて開発したゲーム。ゲーム制作団体の活動の一環として制作した、制限時間内に牧場から脱出する3Dアクションバカゲー。
                  非常に短いゲームであるにもかかわらず、難易度は2種類、エンディング数は4個と多め。NPCの挙動も種類によって異なっている。
                  「ふりーむ！」にてリリース後、とある実況者の方がいつの間にか実況してくださっており、チーム一同で衝撃を受けた。
                  隠しショートカットルートがあるが、実際はショートカットの方が難易度が高い。`,
    image1title: "インゲームの様子",
    image1: "/img/egg/egg.jpg",
    image2title: "リザルト画面",
    image2: "/img/egg/result.png",
    image3title: "制作したフィールド",
    image3: "/img/egg/field.jpg",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: `https://youtu.be/0QWq0nlGY3k`,
    release: `https://www.freem.ne.jp/win/game/26788`,
    github: `https://github.com/twogod23/teamw`,
  },
  blumull: {
    title: "BluMüll",
    thumbnail: "/img/blumull/site.PNG",
    genre: { program: true, design: true, plan: true },
    date: "2022年2月",
    period: "1週間程度",
    member: "4人(プログラマーのみ)",
    tasks: `企画…原案、プロダクト名、プレゼン等
            デザイン…全般
            プログラミングと実装…ジオタグデータ取得実装、画像投稿機能、レイアウト調整など`,
    skill: "Python、HTML、JavaScript、CSS、SQLite3、Flask、Leaflet、GitHub",
    award1: "none",
    award2: "none",
    description: `人生で初めて参加したハッカソン「KC3Hack2022」でチーム制作したユーザー投稿型Webマッピングサービス。
                  SDGsの中から「11 住み続けられるまちづくりを」を取り上げ、ポイ捨て問題や環境保全意識の低さに着目し、
                  ユーザーがゴミ箱の写真をその場で撮影してアップロードするだけでゴミ箱の位置を共有できるサービスを制作した。
                  学年混合チームも初、メンバーも初対面、使用言語や技術も経験0の状態でスタートしたが、
                  制作を進めながらインターネットで知識をかき集め、プログラミングからデザイン、企画まで多くを担当した。`,
    image1title: "制作したマップピン",
    image1: "/img/blumull/pin.jpg",
    image2title: "制作したロゴ",
    image2: "/img/blumull/logo.png",
    image3title: "没のロゴとピン",
    image3: "/img/blumull/botsu.jpg",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "https://youtu.be/_rGO-CjPS5g",
    release: "none",
    github: "https://github.com/kc3hack/2022_b",
  },
  webdesign: {
    title: "地元紹介サイト+α",
    thumbnail: "/img/webdesign/matsubara.png",
    genre: { program: true, design: true, plan: false },
    date: "2022年4月～2022年8月",
    period: "1週間～数週間程度",
    member: "1人",
    tasks: `none`,
    skill: "HTML、JavaScript、CSS、PHP",
    award1: "none",
    award2: "none",
    description: `大学2年生前期の「ウェブデザイン演習」を通して制作したWebサイト5つをまとめたもの。
                  「お絵描き投稿サイト」「プログラミング学習支援サイト」「掲示板サイト」「松原市紹介サイト(名所紹介と神社紹介)」がある。
                  地図の追加、お絵描き機能の実装など、なるべく講義以上の学びを得られるように様々な機能を盛り込んで制作した。`,
    image1title: "プログラミング学習支援サイト",
    image1: "/img/webdesign/programming.png",
    image2title: "お絵描き投稿サイト",
    image2: "/img/webdesign/illust.png",
    image3title: "神社紹介サイト",
    image3: "/img/webdesign/shrine.png",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "https://github.com/kula17524/WebDesignExercises",
  },
  software: {
    title: "リモートに適したソフトウェア提案",
    thumbnail: "/img/remotesoftware/pos.png",
    genre: { program: false, design: true, plan: true },
    date: "2022年5月頃",
    period: "1週間程度?",
    member: "1人",
    tasks: `none`,
    skill: "Adobe Illustrator",
    award1: "none",
    award2: "none",
    description: `大学2年生前期の「デザイン基礎概論」で提出したペラ1企画書。
                  「みんなで一緒に、スムーズに。」をコンセプトとしており、Withコロナ時代のリモートワークと出社業務の混合に適した、
                  オールインワンのタスク管理ソフトを提案した。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  mouse: {
    title: "マウスデザインとポスター制作",
    thumbnail: "/img/mouse/poster.jpg",
    genre: { program: false, design: true, plan: true },
    date: "2022年7月～2022年8月頃",
    period: "1か月～2か月程度",
    member: "1人",
    tasks: `none`,
    skill: "Adobe Illustrator、Adobe Lightroom、石粉粘土など",
    award1: "none",
    award2: "none",
    description: `大学2年生前期の「モデリングデザイン」で制作したマウス。
                  はじめに既存のマウスについてレビューや形状などを調査し、人それぞれの好みや持ち方があることから、
                  エルゴノミクスと通常マウスの両方を兼ね備えたマウスをデザインした。
                  さらに、デザインしたマウスについて石粉粘土を用いて模型を作成、撮影し、その画像を用いたポスターとコンセプトパネルを制作した。`,
    image1title: "コンセプトパネル",
    image1: "/img/mouse/concept.jpg",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  money: {
    title: "課金してもらえるゲームとは",
    thumbnail: "/img/money/title.png",
    genre: { program: false, design: false, plan: true },
    date: "2022年10月～2022年12月",
    period: "2か月程度",
    member: "1人(KJ法のみ4人程度)",
    tasks: `none`,
    skill: "Canva、KJ法、ISM法、AHP法",
    award1: "none",
    award2: "none",
    description: `大学2年生後期の「デザイン企画論A」で提出したレポート。
                  まずは「ゲーム」に興味があるメンバーで「課金してもらえるゲームはどんなゲームか」について意見を出し合い、その後KJマップを作成した。
                  さらに、意見の中から特に重要だと考えられる課金理由30項目を抽出し、ISM法やAHP法を用いて分析し、考察を行った。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "レポート",
    pdf1: "money",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  package: {
    title: "製品パッケージとブースのデザイン",
    thumbnail: "/img/package/mikuji.png",
    genre: { program: false, design: true, plan: true },
    date: "2022年10月～2022年12月",
    period: "2か月程度",
    member: "1人",
    tasks: `none`,
    skill: "Adobe Illustrator、Adobe Lightroom、SketchUp",
    award1: "none",
    award2: "none",
    description: `大学2年生後期の「デザイン表現演習」で提出したレポート。
                  パッケージの型紙をベースに提案する製品を「えんぴつ御籤」に決め、パッケージと展示ブースのデザインを行った。
                  その後、SketchUpを用いて3Dモデルを作成し、コンセプトパネルを制作した。
                  子どもが息抜きにおみくじを引いたり、子どもにえんぴつ御籤をプレゼントする保護者の方が応援メッセージを書き込んだりできるデザインにした。`,
    image1title: "パッケージデザイン",
    image1: "/img/package/pack.jpg",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  rhythm: {
    title: "スマホ向けリズムゲーム分析",
    thumbnail: "/img/gamekj/title.png",
    genre: { program: false, design: false, plan: true },
    date: "2022年12月～2023年1月",
    period: "2か月程度",
    member: "1人",
    tasks: `none`,
    skill: "Canva",
    award1: "none",
    award2: "none",
    description: `大学2年生後期の「デザイン企画論B」で提出したレポート。
                  当時リズムゲームにドハマりしていたことから、人気ランキング上位のスマートフォン向けリズムゲームを30個選び、多変量解析により人気要因の分析を行った。
                  なお、「課金してもらえるゲームとは」の続きとして取り組んだものである。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "レポート",
    pdf1: "gamekj",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  seikyo: {
    title: "大学生協アプリの問題点分析",
    thumbnail: "/img/seikyoapp/negative.png",
    genre: { program: true, design: false, plan: false },
    date: "2023年1月頃",
    period: "1週間～数週間程度",
    member: "1人",
    tasks: `none`,
    skill: "Python、BERT、Mecab、JupyterNotebook",
    award1: "none",
    award2: "none",
    description: `大学2年生後期の「データサイエンス応用」で提出したレポート。
                  ICカード廃止やアプリ導入に伴い不満が噴出していた大学生協アプリ(公式)について、ストアレビューを基に分析を行った。
                  感情分析や形態素解析よりレビューの妥当性とアプリの問題点について分析、考察した。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "レポート",
    pdf1: "seikyo",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  lume: {
    title: "Lume.",
    thumbnail: "/img/lume/title.png",
    genre: { program: true, design: true, plan: true },
    date: "2022年12月～2023年2月頃",
    period: "3か月程度",
    member: "1人",
    tasks: `none`,
    skill: "Java、JMonkeyEngine、Blender",
    award1: "講義内学生投票　1位",
    award2: "none",
    description: `大学2年生後期の「情報システム開発演習」で制作したネットワーク対戦型3DFPSゲーム。
                  本来は事前に配布されたオセロのサンプルコードに改良を加える方式で対戦型〇〇ゲームを制作する講義だが、許可を得て3Dのゲームを制作した。
                  スタート時は真っ暗な状態から始まり、射撃と同時に自身の位置に灯りがともる。5点先取することで勝利となる。
                  フィールドやキャラクターなどのモデリング、プログラミングなど、音源以外は全て自作した。`,
    image1title: "フィールドの様子",
    image1: "/img/lume/lume.png",
    image2title: "対戦中の様子",
    image2: "/img/lume/lume2.png",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "https://youtu.be/yCdx1rNG1Lg",
    release:
      "https://drive.google.com/drive/folders/1v1IT3laba6fsQuLkS7hUQFJakXF83B7T?usp=drive_link",
    github: "https://github.com/kula17524/lume",
  },
  kotatsu: {
    title: "走れ！撃て！KOTATSU-1グランプリ",
    thumbnail: "/img/kotatsu/kotatsu1.jpg",
    genre: { program: true, design: true, plan: true },
    date: "2023年2月～2023年3月頃",
    period: "1～2か月程度",
    member: "8人(プログラマー5名、サウンドクリエイター1名、3Dデザイナー2名)",
    tasks: `企画…アイデア出し、仕様書作成
            デザイン…メインキャラクターデザイン
            プログラミングと実装…NPC実装、障害物実装、スコア管理実装、順位管理実装(補助と一部担当)、プレイヤー実装(補助)`,
    skill: "C#、Unity、GitHub",
    award1: "none",
    award2: "none",
    description: `ゲーム制作団体の活動の一環として制作した、ジェットエンジン付きのコタツで爆走する3Dレースシューティングゲーム。
                  学年混合チームで制作し、自分の担当のプログラミング以外にコンフリクト修正やプログラミングのサポートなども行った。
                  後輩も自分も新しい経験を積めるよう、後輩にプレイヤーなどを担当してもらい、自分は順位やスコアなどの未経験部分とNPCを担当した。`,
    image1title: "プレイ中の様子",
    image1: "/img/kotatsu/kotatsu2.jpg",
    image2title: "障害物爆破の様子",
    image2: "/img/kotatsu/kotatsubomb.jpg",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "https://x.com/cgp_wakayama/status/1643896323702407173?s=46",
    release: "none",
    github: "none",
  },
  heater: {
    title: "ヒーターデザインとECサイト",
    thumbnail: "/img/heater/top.png",
    genre: { program: true, design: true, plan: true },
    date: "2023年4月下旬～2023年8月上旬",
    period: "3か月程度",
    member: "1人(初期調査のみ3人)",
    tasks: `none`,
    skill: "HTML、JavaScript、CSS、Autodesk Fusion360、Adobe Lightroom",
    award1: "none",
    award2: "none",
    description: `大学3年生前期の「メディアデザインセミナー」で制作したヒーターに関するレポートと製品デザインおよびサイト。
                  はじめに既存のヒーターについて調査し、多変量解析を用いて分析を行った。
                  その後「人もドリンクも温められるヒーター」を考案。デザインとモデリングを行い、そのヒーターを販売促進するECサイトのモックアップを制作した。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "ヒーターの分析レポート",
    pdf1: "heater_report",
    pdf2title: "ECサイトのコンセプト",
    pdf2: "heater_concept",
    url: "none",
    release: "none",
    github: "https://github.com/kula17524/HeaterECsite_prototype",
  },
  apart: {
    title: "アパートデザイン",
    thumbnail: "/img/apart/page1.png",
    genre: { program: false, design: true, plan: true },
    date: "2023年4月下旬～2023年8月上旬",
    period: "3か月程度",
    member: "1人",
    tasks: `none`,
    skill: "SketchUp、Adobe Lightroom",
    award1: "none",
    award2: "none",
    description: `大学3年生前期の「インテリアデザイン論」で制作したワーケーション用アパートのデザイン。
                  ペルソナを「フリーランスに転向する旅行好きな30代男性ライター」とし、動線に配慮しながら内装デザインを行った。
                  「古都鎌倉に息づく和モダンの家」をコンセプトとしてモデルの製作と撮影、コンセプトパネルも制作した。`,
    image1title: "コンセプトパネル(詳細)",
    image1: "/img/apart/page2.png",
    image2title: "ペルソナボード",
    image2: "/img/apart/persona.png",
    image3title: "初期コンセプトボード",
    image3: "/img/apart/idea.png",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  reocom: {
    title: "ReO.com",
    thumbnail: "/img/reocom/title.png",
    genre: { program: true, design: true, plan: true },
    date: "2023年4月下旬～2023年8月下旬",
    period: "4か月程度",
    member: "3人(プログラマー3名、うち1名はメインデザイナー兼任)",
    tasks: `企画…全般
            デザイン…一部ボタン作成
            プログラミング・実装…ログイン・ログアウト・メニュー・原稿リストの実装、レスポンシブ対応、発表練習用各種機能実装
            (詳細はサイト内に記載)`,
    skill: "HTML、JavaScript、CSS、Firebase、GitHub",
    award1: "none",
    award2: "none",
    description: `大学3年生前期の「デザイン情報総合演習」で制作し後日リリースした、発表支援Webアプリ。
                  発表時の時間配分に着目し、発表時間の目安が表示される原稿の作成機能や発表練習機能、本番用のプロンプター機能が実装されている。
                  メンバーのチーム開発経験が少なかったため、メインプログラマーとしてだけでなくプロジェクトマネージャーとしても活動した。
                  講義終了後にさらに開発を進め、U-22プログラミングコンテストにも応募した作品である。`,
    image1title: "原稿リスト画面",
    image1: "/img/reocom/list.png",
    image2title: "原稿編集画面",
    image2: "/img/reocom/new.png",
    image3title: "発表練習画面",
    image3: "/img/reocom/practice.png",
    pdf1title: "企画書",
    pdf1: "reocom_plan",
    pdf2title: "使用マニュアル",
    pdf2: "reocom_guide",
    url: "https://youtu.be/hQp4N2M1NKM",
    release: "https://reo-com.web.app",
    github: "https://github.com/kula17524/OSS",
  },
  nusumigui: {
    title: "ぬすみぐいなう！",
    thumbnail: "/img/nusumigui/title.png",
    genre: { program: true, design: false, plan: true },
    date: "2023年10月",
    period: "2日",
    member: "5人(学生4名、社員1名、プログラマーのみ)",
    tasks: `企画…アイデア出し等
            プログラミング・実装…アウトゲームの実装(スタート画面・リザルト画面)`,
    skill: "C#、Unity、SourceTree",
    award1: "none",
    award2: "none",
    description: `株式会社カプコン様主催の2daysインターンシップCAPCOMHackathon2023で制作した2Dアクションゲーム。
                  画面の回転、毒リンゴ、巨大化など様々なギミックに耐えながらぴったり40個のリンゴを集めるとクリアとなる。
                  人生初の2Dゲーム開発。`,
    image1title: "プレイ中の様子",
    image1: "/img/reocom/list.png",
    image2title: "ギミックの様子",
    image2: "/img/reocom/new.png",
    image3title: "リザルト画面の様子",
    image3: "/img/reocom/practice.png",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "https://youtu.be/MbwFOSQ9FXo",
    release: "none",
    github: "none",
  },
  curler: {
    title: "ビューラーの分析とデザイン",
    thumbnail: "/img/nusumigui/title.png",
    genre: { program: false, design: true, plan: true },
    date: "2023年11月～2024年2月頃",
    period: "3か月程度",
    member: "分析と実験4人、デザイン1人",
    tasks: `none`,
    skill: "Blender、Adobe Lightroom",
    award1: "none",
    award2: "none",
    description: `研究室での企業プロジェクトとして既存のビューラーについてプロトコル分析を行い、デザインを提案した。
                  被験者の瞼形状が多様であったこと、既存ビューラーが特定の瞼形状タイプに合わせてデザインされていたことから、
                  カーブの深さを自在に変えられる可変式ビューラーを提案した。`,
    image1title: "デザインの詳細",
    image1: "/img/curler/curler2.png",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  kawachi: {
    title: "みなみてかわち！ロゴデザイン",
    thumbnail: "/img/kawachi/logo.jpg",
    genre: { program: false, design: true, plan: false },
    date: "2024年8月",
    period: "1日",
    member: "1人",
    tasks: `none`,
    skill: "ibisPaint",
    award1: "none",
    award2: "none",
    description: `地元に関係するサイトがロゴを募集していたから、という理由だけで応募したサイトロゴ。
                  G7で提供された河内鴨、市の花である「薔薇」、松原六社参りに由来する「鳥居」をあしらい、松原市の有名なものを詰め込んでいる。
                  全体を河内の「河」の形状にし、河内に関係するサイトであることが伝わるようにした。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "none",
  },
  oshikey: {
    title: "Oshikey",
    thumbnail: "/img/oshikey/title.JPG",
    genre: { program: true, design: true, plan: true },
    date: "2024年2月～現在",
    period: "1年以上",
    member: "2人",
    tasks: `企画…全般
            プログラミング・実装…経路案内機能、絞り込み機能、一部ヘルプ、ミニマップ
            ※コンペ時はピン投稿など基本機能実装済みのプログラムを大倉が提供し2人で実装
            ※デザインに関してはコンペ時は大倉が担当し、正式版は外部委託を行った`,
    skill: "TypeScript、React、MUI、Firebase、Leaflet、GitHub",
    award1: "和歌山イノベーションプログラミングコンテスト　企業賞(Link-U賞)",
    award2: "none",
    description: `「推し活×地方創生」をテーマとしたユーザー投稿型Webマッピングサービス。
                  推し活の経済効果やSNSでの推し布教活動に着目し、ユーザーが推しを布教することで地方創生につなげることを目的とした。
                  ピンの絞り込みや経路案内だけでなく、コスプレの可否やグッズ販売の有無など、推し活に特化した検索機能などがある。
                  コンペ終了後に企業バックアップを受けながら開発を進め、2025年1月に正式にリリースした。`,
    image1title: "地図表示",
    image1: "/img/oshikey/oshikey.png",
    image2title: "投稿されたピンの詳細表示",
    image2: "/img/oshikey/oshikey2.png",
    image3title: "コンペ時に作成していたピンやタグ",
    image3: "/img/oshikey/pin.jpg",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "https://wakayama-innovation-lab.relic.co.jp/archive/2023",
    release: "https://oshikey-e4f55.web.app",
    github: "none",
  },
  portfolio: {
    title: "PORTFOLIO",
    thumbnail: "/img/portfolio/portfolio.png",
    genre: { program: true, design: true, plan: true },
    date: "2025年2月～現在",
    period: "数週間程度",
    member: "1人",
    tasks: `none`,
    skill: "TypeScript、React、MUI、Three.js、Firebase、GitHub",
    award1: "none",
    award2: "none",
    description: `もともとはRESUME.idを使用していたが、React-Three-Fiberの学習を兼ねて自作したポートフォリオサイト。
                  Three.jsを使用することによりエフェクト追加が楽しい分、通常よりもレスポンシブ対応がしにくくなるのが悩みどころ。
                  なお、サイト内BGMに関してはshivue Lounge様の「水夢 -swim-」をお借りしている。`,
    image1title: "none",
    image1: "none",
    image2title: "none",
    image2: "none",
    image3title: "none",
    image3: "none",
    pdf1title: "none",
    pdf1: "none",
    pdf2title: "none",
    pdf2: "none",
    url: "none",
    release: "none",
    github: "https://github.com/kula17524/kula-portfolio",
  },
};
